ampOnIcon = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]

ampOffIcon = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

-- caffeine replacement
local caffeine = hs.menubar.new()

function setCaffeineDisplay(state)
    if state then
        caffeine:setIcon(ampOnIcon)
    else
        caffeine:setIcon(ampOffIcon)
    end
end

local function setCaffeineState(state)
    hs.caffeinate.set("system", state)
    hs.caffeinate.set("displayIdle", state)
    setCaffeineDisplay(state)
end

function caffeineClicked()
    setCaffeineState(not hs.caffeinate.get("system"))
end

-- Keep the external display awake whenever we're on the power adapter, so
-- closing the lid enters clamshell mode instead of a full "Clamshell Sleep".
local function syncWithPowerSource()
    setCaffeineState(hs.battery.powerSource() == "AC Power")
end

if caffeine then
    caffeine:setClickCallback(caffeineClicked)
    powerSourceWatcher = hs.battery.watcher.new(syncWithPowerSource):start()
    syncWithPowerSource()
end
